config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :stock_boxes do
      post 'stocking_check', :on => :collection
    end

    get 'stocking' => 'stock_boxes#stocking'
  end
end

app/models/spree/stock_box.rb
module Spree
  class StockBox < ActiveRecord::Base
    #attr_accessible :number, :positionX, :positionY, :positionZ, :quantity, :last_check_at
    before_validation :generate_box_number, on: :create
    has_many :variants

    def total_items
      if variants.size > 0
        variants.collect{ |v| v.stock_items.collect(&:count_on_hand).reduce(:+) }.compact.reduce(:+)
      else
        0
      end
    end

    def generate_box_number
      alphabet = ('A'..'Z').to_a
      integer = 0
      leter = 0
      record = true
      while record
        number = "#{alphabet[leter]}#{integer}"
        record = self.class.where(number: number).first
        if integer > 9
          integer = 0
          letter += 1
        else
          integer += 1
        end 
      end
      self.number = number if self.number.blank?
      self.number
    end

     def efforts
      Spree::Effort.where(object_type: "Spree::StockBox", object_id: id)
    end
  
  end
end

app/controllers/spree/admin/stock_boxes_controller.rb
# coding: utf-8
require 'barby'
require 'barby/barcode/code_128'
require 'barby/outputter/png_outputter'

module Spree
  module Admin
    class StockBoxesController < ResourceController #Spree::Admin::BaseController

      # GET /stock_boxes
      # GET /stock_boxes.json
      def index
        params[:order_by] ||= "name"
        per_page = 20
        params[:page] ||= "1"

        @stock_boxes = case params[:order_by]
          when "nonempty"
            StockBox.where("quantity > ?", 0).order(:number).page(params[:page]).per(per_page)
          when "quantity"
            Kaminari.paginate_array(StockBox.all.sort_by{ |b| b.total_items }.reverse).page(params[:page]).per(per_page)
          else
            StockBox.order(:number).page(params[:page]).per(per_page)
        end

        respond_to do |format|
          format.html # index.html.erb
          format.json { render json: @stock_boxes }
        end
      end

      # GET /stock_boxes/1
      # GET /stock_boxes/1.json
      def show
        @stock_box = StockBox.find(params[:id])
        stock_state_priority = ["Estoque","Reservado","Perdido","Vendido"].reverse
        @variants = @stock_box.variants#.sort_by { |v| [v.count_on_hand, stock_state_priority.index(v.stock_state)] }.reverse
        @variant_names = []
        @variants.each do |variant|
          @variant_names.push(variant.name)
        end

        @barcode_path = "/tmp/barcode_stockbox_#{@stock_box.number}.png"
        unless FileTest.exist?("#{Rails.root}/public#{@barcode_path}")
          barcode = Barby::Code128A.new(@stock_box.number)
          File.open("#{Rails.root}/public#{@barcode_path}", 'w+') do |f|
            f.write barcode.to_png(:margin => 3, :xdim => 2, :height => 65)
          end
        end

        if params[:print]
          respond_to do |format|
            format.html { render action: "show", layout: "spree/layouts/blank" }
          end
        else
          respond_to do |format|
            format.html # show.html.erb
            format.json { render json: { stock_box: @stock_box, variants: @variants, variant_names: @variant_names } }
          end
        end
      end

      # GET /stock_boxes/new
      # GET /stock_boxes/new.json
      def new
        @stock_box = StockBox.new

        respond_to do |format|
          format.html # new.html.erb
          format.json { render json: @stock_box }
        end
      end

      # GET /stock_boxes/1/edit
      def edit
        @stock_box = StockBox.find(params[:id])
      end

      # POST /stock_boxes
      # POST /stock_boxes.json
      def create
        @stock_box = Spree::StockBox.new(stock_box_params)
        @stock_box.quantity = 1 unless @stock_box.quantity

        respond_to do |format|
          if @stock_box.save
            format.html { redirect_to admin_stock_boxes_url, notice: 'Caixa de estoque criada com sucesso.' }
            format.json { render json: @stock_box, status: :created, location: @stock_box }
          else
            format.html { render action: "new" }
            format.json { render json: @stock_box.errors, status: :unprocessable_entity }
          end
        end
      end

      # PUT /stock_boxes/1
      # PUT /stock_boxes/1.json
      def update
        @stock_box = StockBox.find(params[:id])

        respond_to do |format|
          if @stock_box.update_attributes(params[:stock_box])
            format.html { redirect_to admin_stock_boxes_url, notice: 'Caixa de estoque atualizada com sucesso.' }
            format.json { head :no_content }
          else
            format.html { render action: "edit" }
            format.json { render json: @stock_box.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /stock_boxes/1
      # DELETE /stock_boxes/1.json
      def destroy
        @stock_box = StockBox.find(params[:id])
        @stock_box.destroy

        respond_to do |format|
          format.html { redirect_to admin_stock_boxes_url }
          format.json { head :no_content }
        end
      end

      def stocking

      end

      def stocking_check
        @box = Spree::StockBox.find_by_number(params[:box_number])
        if params[:field_action] == "open"

          if @box
            task = Spree::Task.where(name: "Stocking").first
            effort = @box.efforts.where(task_id: task.id).first_or_create
         
            effort.started_at ||= Time.now
            effort.user_id ||= spree_current_user.id
            effort.object_id ||= @box.id
            effort.object_type ||= "Spree::StockBox"
            effort.description ||= "Estocando produtos na caixa #{params[:box_number]}"
            effort.save


          end

          check = "open"
          @start_at = DateTime.now
          respond_to do |format|
            format.js { render "box_open" }
          end
        end

        if params[:field_action] == "insert"
          check = "insert"

          @new_image = nil
          registered_items = params[:registered_items]

          new_item = params[:stock_items].split(",").last.squish.downcase
          @last_entry = new_item
          box_number = params[:box_number].downcase

          @new_value = registered_items
          if new_item == box_number
            respond_to do |format|
              format.js { render "box_close" }
            end
          elsif new_item.to_i > 10000000000 and new_item.to_i < 20000000000 and new_item.to_i.to_s == new_item

            variant = Spree::Variant.find_by_sku(new_item)
            if variant
              @check_message = 2
              if variant.count_on_hand == 0
                @check_message = 4
                order = variant.product.order
                shipment = order ? order.shipments.last : nil
                if shipment
                  @check_message = 1 if shipment.state == "shipped" || shipment.state == "ready"
                end
              end
            else
              name = "Produto em processo de cadastramento"
              p = Spree::Product.new(sku: new_item, price: 0, name: name, permalink: name.parameterize)
              p.save(validate: false)
              @check_message = 3
            end

            if @check_message > 1
              new_value = [registered_items, new_item, ", "] - [""]
              @new_value = new_value.join("") if new_value
            end

            product = variant.product if variant
            images = product.images if product
            if images && !images.empty?
              attachment = images.first.attachment
              @new_image = attachment.url(:product) if attachment
            end

            respond_to do |format|
              format.js { render "box_insert" }
            end
          else
            @old_value = registered_items
            respond_to do |format|
              format.js { render "box_insert_error" }
            end
          end
        end

        if params[:field_action] == "close"
          check = "close"

          if @box
            task = Spree::Task.where(name: "Stocking").first
            effort = @box.efforts.where(task_id: task.id).first_or_create
         
            effort.completed_at ||= Time.now
            effort.user_id ||= spree_current_user.id
            effort.object_id ||= @box.id
            effort.object_type ||= "Spree::StockBox"
            effort.quantity = (params[:registered_items].split(',').size) -1
            effort.save


          end


          registerer_id = spree_current_user.id
          total_registered_items = 0

          registered_items = params[:registered_items]
          registered_items.split(", ").each do |v|
            variant = Spree::Variant.find_by_sku(v)
            variant.update_column(:stock_box_id, @box.id)
            variant.update_column(:stocked_by_id, registerer_id)
            total_registered_items += 1

            effort.stock_events.create(variant: variant, state: Spree::StockEvent.states[:GUARDADO], stock_box: @box)
          end

          # start_at = params[:effort_starts_at]
          # end_at = DateTime.now
          # activity = Spree::Activity.find_by_name("Estoque")
          # task = Spree::Task.where(name:"Stocking").where(activity_id:activity.id).first
          # effort = Spree::Effort.new(description: "Estocando produtos na caixa #{@box.number}", started_at: start_at)
          # effort.user_id = registerer_id
          # effort.task_id = task.id
          # effort.object_id = @box.id
          # effort.object_type = "Spree::StockBox"
          # effort.quantity = total_registered_items
          # effort.completed_at = end_at
          # effort.save

          respond_to do |format|
            format.js { render "page_reload" }
          end

        end

        render nothing: true unless check
      end

      private

      def stock_box_params
        params.require(:stock_box).permit(:number, :last_check_at, :positionX, :positionY, :positionZ, :quantity)
      end
    end
  end
end

app/views/spree/admin/stock_boxes/_form.html.erb
<%= form_for([:admin, @stock_box]) do |f| %>
  <% if @stock_box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stock_box.errors.count, "error") %> prohibited this stock_box from being saved:</h2>

      <ul>
      <% @stock_box.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :last_check_at, "Data da última checagem:" %><br />
    <%= f.text_field :last_check_at, :class => 'datepicker' %>
  </div>
  <div class="field">
    <%= f.label :positionX %><br />
    <%= f.text_field :positionX %>
  </div>
  <div class="field">
    <%= f.label :positionY %><br />
    <%= f.text_field :positionY %>
  </div>
  <div class="field">
    <%= f.label :positionZ %><br />
    <%= f.text_field :positionZ %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/spree/admin/stock_boxes/box_close.js.erb
$("#stock_items").val("<%= @new_value %>");
$("#field3 form").trigger("change");
$("#show-last-item").html('');

app/views/spree/admin/stock_boxes/box_insert.js.erb
<% if @check_message > 1 %>
$(".registered_items").val("<%= @new_value %>");
$("#field2 .check").html("<%= j (image_tag 'admin/ok.png') %>");
<% else %>
alert("Produto indisponível!");
$("#field2 .check").html("<%= j (image_tag 'admin/not.png') %>");
<% end %>

<% if @new_image %>
  $("#show-last-item").html("<img src='<%= @new_image %>' />");
<% else %>
  message = "<h1 style='text-align:center;margin-top:150px;font-size:3em;'>";
  message += "SEM IMAGEM<br />";
  message += "<span class='green'><%= @last_entry %></span>";
  <% if @check_message == 3 %>
    message += "<br /><span style='font-size:0.5em'>Item não cadastrado</span>";
  <% end %>
  message += "</h1>";
  $("#show-last-item").html(message);
<% end %>

// http://stackoverflow.com/questions/6003300/how-to-place-cursor-at-end-of-text-in-textarea-when-tabbed-into
// function focusEndOfTextarea(el) {
//   if (typeof el.selectionStart == "number") {
//     el.selectionStart = el.selectionEnd = el.value.length;
//   } else if (typeof el.createTextRange != "undefined") {
//     el.focus();
//     var range = el.createTextRange();
//     range.collapse(false);
//     range.select();
//   }
// }
//
// setTimeout(function() {
//   $("#stock_items").val("<%= @new_value %>");
//   var textarea = document.getElementById("stock_items");
//   focusEndOfTextarea(textarea);
// }, 1);
$("#stock_items").val("<%= @new_value %>");
$("#stock_items").focus()

app/views/spree/admin/stock_boxes/box_open.js.erb
<% if @box %>
$(".box").val("<%= @box.number %>");
$("#field1 .check").html("<%= j (image_tag 'admin/ok.png') %>");
$("#field2").show();
$("#field2 #stock_items").focus();
$("#show-last-item").html('');
$("#effort_starts_at").val("<%= @start_at %>");
<% else %>
$("#field1 .check").html("<%= j (image_tag 'admin/not.png') %>");
$("#field1 #box_number").select().focus();
$("#show-last-item").html('');
$("#effort_starts_at").val('');
<% end %>

app/views/spree/admin/stock_boxes/edit.html.erb
<% content_for :page_actions do %> 
<li><%= button_link_to "Voltar", admin_stock_boxes_path, :icon => 'icon-arrow-left' %></li>
<% end %>

<% content_for :page_title do %>
<h1>Editando caixa de estoque #<%= @stock_box.number %></h1>
<% end %>

<%= render 'form' %>

app/views/spree/admin/stock_boxes/index.html.erb
<style type="text/css" media="print"> /* *:not(#print) { display: none; } */</style>
<%= render :partial => 'spree/admin/shared/sub_menu/configuration' %>
<% if Rails.env.development? %>
  <script> var webPrefix = "https://localhost:3000/admin/stock_boxes/"; </script>
<% else %>
  <script> var webPrefix = "https://www.retroca.com.br/admin/stock_boxes/"; </script>
<% end %>
<% content_for :page_actions do %> 
  <li><%= button_link_to "Nova Caixa", new_admin_stock_box_path %></li>
  <% if params[:order_by] == "non_empty" %>
    <li><%= button_link_to "Todas", admin_stock_boxes_path %></li>
  <% else %>
    <li><%= button_link_to "Apenas caixas não-vazias", admin_stock_boxes_path(order_by: "non_empty") %></li>
  <% end %>
<% end %>

<% content_for :page_title do %>
  Caixas de Estoque
<% end %>

<table class="table">
  <thead><tr>
    <th>Number</th>
    <th>Positionx</th>
    <th>Positiony</th>
    <th>Positionz</th>
    <th>
      <% if params[:order_by] == "quantity" %>
        <%= link_to "Quantity", admin_stock_boxes_path, class:"sort_link asc" %>
      <% else %>
        <%= link_to "Quantity &dtrif;".html_safe, admin_stock_boxes_path(order_by: "quantity"), class:"sort_link desc" %>
      <% end %>
    </th>
    <!--<th>Items</th>-->
    <th data-hook="admin_orders_index_header_actions" class="actions"></th>
  </tr></thead>
<tbody>
<% @stock_boxes.each do |stock_box| %>
  <tr>
    <td><%= link_to stock_box.number, admin_stock_box_path(stock_box) %></td>
    <td><%= stock_box.positionX %></td>
    <td><%= stock_box.positionY %></td>
    <td><%= stock_box.positionZ %></td>
    <td><%= stock_box.total_items %></td>
    <td class='actions align-center' data-hook="admin_orders_index_row_actions">
			<%= link_to_edit_url edit_admin_stock_box_path(stock_box), :no_text => true %>
			<%= link_to_delete stock_box, :no_text => true, :url => admin_stock_box_path(stock_box) %>
      <%= button_link_to "Imprimir", admin_stock_box_path(stock_box, {print: true}) %>
		</td>
  </tr>
<% end %>
<tbody>
</table>

<%= paginate @stock_boxes %>

<script type="text/javascript">
$(".actions a.button").on("click", function(e){
  e.preventDefault();
  window.open($(this).attr("href"),'popUpWindow','scrollbars=yes,menubar=no');
});
</script>

app/views/spree/admin/stock_boxes/new.html.erb
<h1>Nova caixa de estoque stock_box</h1>

<%= render 'form' %>

<%= link_to 'Volta', admin_stock_boxes_path %>

app/views/spree/admin/stock_boxes/page_reload.js.erb
window.location.reload();

app/views/spree/admin/stock_boxes/show.html.erb
<% content_for :head do %>
<style type="text/css">
@media print {
	#progress, header, #admin-menu, #content-header .page-actions, #sidebar, .twelve.columns > br, .twelve.columns > a {
		display:none !important;
	}
	img {
		display:none;
	}
}
ul li {
	display: inline-block;
	padding-left:30px;
}
</style>
<% end %>

<%= render :partial => 'spree/admin/shared/sub_menu/configuration' %>

<% content_for :page_actions do %>
	<li><button onClick="window.print()">Imprimir</button></li>
<% end %>

<% content_for :page_title do %>
  Peças na Caixa #<%= @stock_box.number %>
<% end %>

<% if params[:print] %>
<h1>Peças na Caixa #<%= @stock_box.number %></h1>
<% else %>
<%= image_tag @barcode_path %>
<% end %>

<table class="table">
  <thead>
	<tr>
		<th>SKU</th>
		<th>Nome</th>
		<th>Estoque</th>
	</tr>
  </thead>

	<% @variants.each do |variant| %>
		<tbody>
		  <tr>
		    <td><%= variant.sku %></td>
		    <td><%= link_to variant.name, admin_product_path(variant.product), target: "_blank" %></td>
			<td>
				<%= variant.stock_items.collect(&:count_on_hand).reduce(:+) %>
				<%= "(#{variant.stock_state[0]})" if variant.stock_items.collect(&:count_on_hand).reduce(:+) == 0 %>
			</td>
		  </tr>
		</tbody>
	<% end %>
	<tfoot>
		<tr>
			<td colspan="3">
				<ul>
					<li>(R) = Reservado</li>
					<li>(V) = Vendido</li>
					<li>(P) = Perdido</li>
				</ul>
			</td>
		</tr>
	</tfoot>
</table>

<br />



<br />

<%= link_to 'Voltar', admin_stock_boxes_path %>

<% if params[:print] %>
<script type="text/javascript">
window.print()
</script>
<% end %>

app/views/spree/admin/stock_boxes/stocking.html.erb
<% content_for :page_actions do %>
		<li><%= button_link_to t(:back), admin_orders_path, :icon => 'icon-arrow-left' %></li>
<% end %>

<% content_for :page_title do %>
		Armazenamento de peças no estoque
<% end %>

<div id="stocking-page" class="seven columns row">

	<div class="col-md-6 col-sm-6">
		<div class="form-row" id="field1">
			<h6>Registrador:</h6>
					<%= text_field_tag 'registerer', spree_current_user.firstname, :disabled=>true %>
					<br /><br />

			<h6>Escaneie a caixa desejada</h6>
			<%= form_tag(stocking_check_admin_stock_boxes_path, method: :post) do %>
					<%= hidden_field_tag 'field_action', 'open' %>
					<%= text_field_tag 'box_number', '', placeholder: 'Número da caixa' %>
					<span class="check">carregando..</span>
					<br /><br />
					<%= submit_tag("Não me clique") %>
			<% end %>
		</div>

		<div class="form-row" id="field2" style="display:none;">
			<%= form_tag(stocking_check_admin_stock_boxes_path, method: :post) do %>
					
					<%= hidden_field_tag 'field_action', 'insert' %>
					<%= hidden_field_tag 'box_number', '', class: "box" %>
					<%= hidden_field_tag 'registered_items', '', class: "registered_items" %>
					<%= hidden_field_tag 'box_number', '', class: "box" %>
					
					<h6>Escaneie as peças a serem guardadas</h6>
					<%= text_area_tag 'stock_items', '', rows: 10, cols: 50, placeholder: 'SKU das peças a serem armazenadas' %>
					<span class="check"></span>
					<br /><br />
					<%= submit_tag("Não me clique") %>
			<% end %>
		</div>
	</div>

	<div class="col-md-6 col-sm-6">
		<div class="form-row" id="field3" style="display:none;">
			<%= form_tag(stocking_check_admin_stock_boxes_path, method: :post) do %>
					<%= hidden_field_tag 'field_action', 'close' %>
					<%= hidden_field_tag 'box_number', '', class: "box" %>
					<%= hidden_field_tag 'registered_items', '', class: "registered_items" %>
					<%= hidden_field_tag 'effort_starts_at','' %>
					<span class="check"></span>
			<% end %>
		</div>

		<div class="form-row" id="next-box" style="display:none;">
			<h6 class="form-row">Caixa fechada!</h6>
			<%= button_link_to "Próxima caixa", "/admin/stocking" %>
		</div>

		<div id="show-last-item" class="seven columns"></div>
	</div>
</div>

<script type="text/javascript">
	console.log("ALL READY!");

	$("#box_number").focus();
	$("#field1 .check").html('');

	$("form").on("change", function(){
		console.log("Form #" + $(this).attr("id") + " changed");
		$("#show-last-item").html("carregando..");
		$.post($(this).attr('action'), $(this).serialize(), null, "script");

	});

	$("input[type=submit]").on("click", function(e){
		e.preventDefault();
		console.log("Submited form");
		var form = $(this).closest("form");
		$.post($(form).attr('action'), $(form).serialize(), null, "script");

	});
</script>